#!/usr/bin/python

#
# Admyral is a minimal keyboard driven web browser written in Python and Qt
#
# Author    Yassine Maaroufi
# Licence   GPLv3
# 

import sys, re

from PyQt4.QtCore import *
from PyQt4.QtGui import *
from PyQt4.QtWebKit import *

TABS = []						# Tabs list

def closeWidget(parent, w):
	parent.show()	#
	w.close()
	w.destroy()
	parent.setFocus()
	#parent.focusPreviousChild()

def changeURL(parent, w):
	parent.show()	#
	url = w.text()
	if not url.startswith('http://'):
		r = re.compile('^[a-zA-Z0-9\-]*\.?[a-zA-Z0-9\-]*\.[a-z]{2,4}')
		if r.findall(url) == [] :
			url = 'http://www.google.com/search?q=' + url
		else:
			url = 'http://' + url

	parent.setUrl(QUrl(url))
	w.close()
	w.destroy()

def URLBar(parent):
	#w = QLineEdit(parent)
	w = QLineEdit()
	w.setText(parent.url().toString())
	#w.resize(parent.width()/3, 20)
	#w.move(parent.width()/3, parent.height()/2)
	w.setFocus()
	QShortcut("Esc", w, activated = lambda: closeWidget(parent, w))
	QObject.connect(w, SIGNAL('returnPressed()'), lambda: changeURL(parent, w))
	w.show()
	parent.hide()

def search(parent, w):
	w.close()
	w.destroy()
	parent.show()
	#parent.findText('', HighlightAllOccurrences)
	#parent.findText(w.text(), HighlightAllOccurrences)
	parent.findText(w.text())

def searchBar(parent):
	w = QLineEdit()
	w.setFocus()
	QShortcut("Esc", w, activated = lambda: closeWidget(parent, w))
	QObject.connect(w, SIGNAL('returnPressed()'), lambda: search(parent, w))
	w.show()
	parent.hide()

def closeTab(parent):
	global TABS
	TABS[TABS.index(parent) - 1].show()
	TABS.pop(TABS.index(parent))
	parent.close()
	parent.destroy()

def closeTabs():
	for i in TABS:
		i.close()

def callNewTab(parent):
	initTab()
	parent.hide()

def nextTab(parent):
	global TABS
	if len(TABS) > 1:
		n = 0 if (TABS.index(parent) + 1 > len(TABS) - 1) else (TABS.index(parent) + 1)
		TABS[n].show()
		parent.hide()

def prevTab(parent):
	global TABS
	if len(TABS) > 1:
		n = len(TABS) - 1 if (TABS.index(parent) - 1 < 0) else (TABS.index(parent) - 1)
		TABS[n].show()
		parent.hide()

def changeTab(parent, w):
	global TABS
	if len(TABS) > 1:
		n = w.currentRow()
		closeWidget(parent, w)
		parent.hide()
		TABS[n].show()

def listTabs(parent):
	global TABS
	#w = QListWidget(parent)
	w = QListWidget()
	for i in TABS:
		w.addItem(i.title())
	#w.resize(parent.width()/3, parent.height()/3)
	#w.move(parent.width()/3, parent.height()/3)
	w.setFocus()
	QShortcut("Esc", w, activated = lambda: closeWidget(parent, w))
	QShortcut("Return", w, activated = lambda: changeTab(parent, w))
	parent.hide()
	w.show()

def openInNewTab(parent):
	print(QMouseEvent().modifiers())



def initTab():
	global TABS
	v = QWebView()
	v.load(QUrl(url))
	v.setFocus()
	QShortcut("Ctrl+J", v, activated = lambda: prevTab(v))
	QShortcut("Ctrl+K", v, activated = lambda: nextTab(v))
	QShortcut("Ctrl+L", v, activated = lambda: URLBar(v))
	QShortcut("Ctrl+Q", v, activated = closeTabs)
	QShortcut("Ctrl+T", v, activated = lambda: callNewTab(v))
	QShortcut("Ctrl+W", v, activated = lambda: closeTab(v))
	QShortcut("F2", v, activated = lambda: listTabs(v))
	QShortcut("F3", v, activated = lambda: searchBar(v))
	QShortcut("F6", v, activated = lambda: URLBar(v))
	QObject.connect(v, SIGNAL('linkClicked()'), lambda: openInNewTab(v))
	v.show()
	TABS += [v]

url = 'http://www.google.com'	# Default URL
app = QApplication(sys.argv)
initTab()
sys.exit(app.exec_())
